### PR TITLE
A divided zero bug with some trivial changes

### PR DESCRIPTION
**Pull request by ericliang**
Nice work, Raffaele.

The Off-Heap Memory work is deeply involved with what I'm doing now, so I can not wait to checkout it when I first saw it ( The project was incubated by Apache, congratulations ). So what piggyback these trivial changes is my excitement. :D Anyway, hope this project soon graduates from the incubator, and I'll keep a close eye on it.

Regards,
Eric

### CODE REVIEW

**Comment by raffaeleguidi** [comment]
Thank you! But that version is pretty old you should align with apache code
base here in github
Il giorno 18/mag/2012 09:27, "Eric Liang" <
reply@reply.github.com>
ha scritto:

**Comment by ericliang** [comment]
Oops, it is very very old. I'll try this new repository, thanks.  However, the project in your account is such a confusion, you may consider to update it.

**Comment by raffaeleguidi** [comment]
Well, that project is still there just for historical reasons... I guess I
could be blamed forever for my messy project :D

Ciao,
    R

On Fri, May 18, 2012 at 6:07 PM, Eric Liang <
reply@reply.github.com

**Comment by ericliang** [comment]
A good mentality you have. I guess you'll receive continuous pull requests in the future since the old project's watch number is much bigger than the one in apache repository and is still growing. It's ok if it is your desire, but there would also be a slowdown in other people's attempts on it.

**Comment by raffaeleguidi** [comment]
Right. I'll consider updating, thanks for your advice.

Ciao,
     R
Il giorno 19/mag/2012 06:23, "Eric Liang" <
reply@reply.github.com>
ha scritto:

**Pull request closed without merging**
